main: net.eternalproyect.essentials.Essentials
name: EternalEssentials
version: 0.4-BETA
authors:
  - EnzoL_
  - ShaunaFurry
description: Plugin re loco hecho por el duo dinamita
depend:
  - Vault
api-version: 1.14